# Generated by Django 5.0.6 on 2024-06-24 21:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_brand_category_manufacture_unit_inventory_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Warehouse',
        ),
    ]
