# Generated by Django 5.0.6 on 2024-06-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_producttype_typevariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
